name: karman_app
description: "Productivity in your pocket"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.2.3-beta.1+5

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.1.0
  go_router: ^14.2.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  intl: ^0.19.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  slide_to_act: ^2.0.2
  circular_countdown_timer: ^0.2.3
  sleek_circular_slider: ^2.0.1
  audioplayers: ^6.0.0
  just_audio: ^0.9.39
  change_app_package_name: ^1.3.0
  shared_preferences: ^2.3.1
  package_info_plus: ^8.0.1
  table_calendar: ^3.1.2
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.2
  tutorial_coach_mark: ^1.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  vibration: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/icon/icon.png
    - lib/assets/intro/tasks.json
    - lib/assets/intro/habits.json
    - lib/assets/intro/focus.json
    - lib/assets/intro/github.json
    - lib/assets/audio/rain.mp3
    - lib/assets/audio/forest.mp3
    - lib/assets/audio/ocean.mp3
    - lib/assets/audio/night.mp3
    - lib/assets/audio/airplane.mp3
    - lib/assets/audio/subtle_chime.mp3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "lib/assets/images/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "lib/assets/images/icon/foreground.png"
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true
